### ISSUE TITLE
Responding to 2025 KICPA quiz renewal

### ISSUE THREAD

**Issue by yoonseopshin** [yoonseopshin/kicpa-wordquiz#54]
## TODO
- [ ] `CommercialLaw`: Exclude "어음수표법"
- [ ] `Business`: Exclude "생산관리", "마케팅"
- [ ] Added announcement functionality: entry points and above notices
